### ISSUE TITLE
dict parsing in standalones

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/libomax#2]
I know this is a known issue, but it just bit me so I thought I'd make an entry for it.

Is there a solution for standalones? maybe we can get the App name and look inside the bundle contents?

**Comment by maccallum** [comment]
I think it's time to drop support for versions of max that don't support dicts (<6?).

**Comment by ramagottfried** [comment]
+1

maybe we can keep a copy of the current release around somewhere just in case someone needs it?

**Comment by ilzxc** [comment]
This is probably the wrong place to discuss this, but what about the SSA machine support?

**Comment by adrianfreed** [comment]
I agree

**Comment by adrianfreed** [comment]
Realistically maintaining old versions isn't going to happen in the current climate.
It's all we can do to get a tested yearly release out of anything.
Let others do a backport if they need to.

**Comment by equilet** [comment]
referencing original issue:  https://github.com/CNMAT/libomax/issues/2

**Comment by maccallum** [comment]
Support for <5 has been dropped
