### ISSUE TITLE
dict_obj error

### ISSUE THREAD

**Issue by davispolito** [CNMAT/libomax#4]
******************************************************************
*****                    BUILDING LIBOMAX                    *****
******************************************************************
clang -arch x86_64 -O3 -funroll-loops -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.9 -std=c99 -I../max-sdk/source/c74support/max-includes -I../max-sdk/source/c74support/msp-includes -I../pure-data/src -I../libo -I/usr/include  -o omax_dict.o -c omax_dict.c
omax_dict.c:205:4: error: use of undeclared identifier
      'omax_dict_dictobj_register'; did you mean 'omax_dict_dictobj_release'?
                        omax_dict_dictobj_register = CFBundleGetFunction...
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
                        omax_dict_dictobj_release
omax_dict.c:59:20: note: 'omax_dict_dictobj_release' declared here
static t_max_err (*omax_dict_dictobj_release)(t_dictionary *d);
                   ^
omax_dict.c:206:8: error: use of undeclared identifier
      'omax_dict_dictobj_register'; did you mean 'omax_dict_dictobj_release'?
                        if(!omax_dict_dictobj_register){
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
                            omax_dict_dictobj_release
omax_dict.c:59:20: note: 'omax_dict_dictobj_release' declared here
static t_max_err (*omax_dict_dictobj_release)(t_dictionary *d);
                   ^
2 errors generated.
make: *** [omax_dict.o] Error 1

**Comment by maccallum** [comment]
Fixed
